export const routes = {
    register: '/register',
    login: '/login',
    allUsers: '/all-users',
    updateUserRole: '/update-user-role',
    updateUserBlockStatus: '/update-user-block-status',
    deleteUser: '/delete-user',
    user: '/user',
    allCategories: '/all-categories',
    allCollections: '/all-collections',
    getCollectionById:'/get-collection-by-id',
    createCollection: '/create-collection',
    updateCollection: '/update-collection',
    deleteCollection: '/delete-collection',
    allItemsInCollection: '/all-items-in-collection',
    createItem: '/create-item',
    deleteItem: '/delete-item',
    updateItem: '/update-item',
};
