export type TItemInCollection = {
    id: number;
    title: string;
    tags: string[];
    collectionId: number;
    custom_int1?: number;
    custom_int2?: number;
    custom_int3?: number;
    custom_string1?: string;
    custom_string2?: string;
    custom_string3?: string;
    custom_text1?: string;
    custom_text2?: string;
    custom_text3?: string;
    custom_boolean1?: boolean;
    custom_boolean2?: boolean;
    custom_boolean3?: boolean;
    custom_date1?: string;
    custom_date2?: string;
    custom_date3?: string;
};